### ISSUE TITLE
Multiple zoneID errors on line 714 (30C9, 3220, 1060)

### ISSUE THREAD

**Issue by Spor36** [smar000/evohome-Listener#18]
Hi,

First of all thanks for the great work with this listener. I do get some errors with Evo FW3 and version 1.11.0. How can I fix it?

[events.log](https://github.com/smar000/evohome-Listener/files/5348866/events.log)
[evogateway.log](https://github.com/smar000/evohome-Listener/files/5348868/evogateway.log)

**Comment by smar000** [comment]
Line 714 is where the code calls the appropriate decoding function for the message. Unfortunately it is too generic and does not really show where the actual error is occurring.

There have been a number of changes in my internal code since the version you are using, including changes to the opentherm related code (which is where the error appears to be). I will hopefully be pushing the updated version to github in the coming days, and so suggest trying on this once it is released.

EDIT: I've just pushed the python3 version. Pls try this and see how you get on.

**Comment by Spor36** [comment]
Hi Smar000 thanks for the quick replay and of course new Python3 version, great work. I tried it and it worked (probably I made a mistake with the device.json the first time .......

I have two HCE80's and I can't get the status for the actuators (for which I started logging, getting much too hot in some rooms) ... only a couple of messages (3150 zone heat demand) from the first channel of both UFH's. (Is zoneId from actual zones or channel number UFH?) I do get some 'unknown' actuator state messages (3EF0).

Any idea how to get the actuator status from both HCE80's?

[events2(git).txt](https://github.com/smar000/evohome-Listener/files/5361010/events2.git.txt)
[evogateway2.log](https://github.com/smar000/evohome-Listener/files/5361011/evogateway2.log)

**Comment by smar000** [comment]
Good to hear you have it working.

WRT the HCE80, Unfortunately I don't think that it provides zone level data (just an overall heat demand, exactly as you are seeing). The HCC80R however does give individual zone level data.

See https://www.automatedhome.co.uk/vbulletin/showthread.php?6087-evohome-HCE80-UFH-valve-state-decoding-from-radio-signals/page3&highlight=hce80+hcc80r for more info.

**Comment by number42net** [comment]
I ran into the same issue while setting this up this afternoon. It looks like part of the code expecting the devices dict to contain zoneId and other parts expecting zone_id instead.

I've created pull request #19 which should resolve this.

**Comment by smar000** [comment]
This should now be fixed with the latest merge, uploaded a short while ago. I'll close the issue for now, but if the matter is not resolved, please do re-open.
